name: SurrealDB CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
      - name: Start SurrealDB
        uses: surrealdb/setup-surreal@v1
        with:
          surrealdb_version: latest
          surrealdb_port: 8000
          surrealdb_username: root
          surrealdb_password: root
          surrealdb_auth: false
          surrealdb_strict: true
          surrealdb_log: info
          surrealdb_additional_args: --allow-all
